const TempData = [
  {
    unit_id: 20,
    name_code: 'MADURAI HIGH COURT',
    unit_name: 'MHC MADURAI',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: '',
    unit_head_name: '',
    latitude: 13.08704,
    longitude: 80.287279,
  },
  {
    unit_id: 21,
    name_code: 'MADRAS HIGH COURT',
    unit_name: 'MHC CHENNAI',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: '',
    unit_head_name: '',
    latitude: 13.087732500000001,
    longitude: 80.2877015,
  },
  {
    unit_id: 22,
    name_code: 'NLC NEYVELI',
    unit_name: 'NLC NEYVELI',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: '',
    unit_head_name: 'DIG',
    latitude: 11.53104,
    longitude: 79.476517,
  },
  {
    unit_id: 23,
    name_code: 'SOUTH SECTOR HQ CHENNAI',
    unit_name: 'SS HQR CHENNAI',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: 'MHA',
    unit_head_name: 'IG',
    latitude: 13.09,
    longitude: 80.27,
  },
  {
    unit_id: 24,
    name_code: 'BHARAT DYNAMICS LIMITED BHANUR',
    unit_name: 'BDL BHANUR',
    bar_color: 'brown',
    state_name: 'ANDHRA PRADESH',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 16.5,
    longitude: 80.6,
  },
  {
    unit_id: 25,
    name_code: '4TH RESERVE BATTALION SIVAGANGAI',
    unit_name: '4TH RB SIVAGANGAI',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: '',
    unit_head_name: 'CO',
    latitude: 9.847,
    longitude: 78.4836,
  },
  {
    unit_id: 26,
    name_code: 'BANK NOTE PAPER MILL INDIA PVT LTD MYSORE',
    unit_name: 'BNPMIPL MYSORE',
    bar_color: 'lightblue',
    state_name: 'KARNATAKA',
    ministry: '',
    unit_head_name: 'AC',
    latitude: 12.30306,
    longitude: 76.64333,
  },
  {
    unit_id: 27,
    name_code: 'BHARAT  HEAVEY ELECTRONICS LIMITED BANGALORE',
    unit_name: 'BHEL BANGALORE',
    bar_color: 'lightblue',
    state_name: 'KARNATAKA',
    ministry: '',
    unit_head_name: 'AC',
    latitude: 12.93445,
    longitude: 77.611216,
  },
  {
    unit_id: 28,
    name_code: 'BHARAT DYNAMICS LTD KANCHANBAGH',
    unit_name: 'BDL KANCHANBAGH',
    bar_color: 'brown',
    state_name: 'ANDHRA PRADESH',
    ministry: '',
    unit_head_name: 'CO',
    latitude: 16.5,
    longitude: 80.6,
  },
  {
    unit_id: 29,
    name_code: 'BHARAT HEAVY ELECTRICALS LIMITED HYDERABAD',
    unit_name: 'BHEL HYDERABAD',
    bar_color: 'brown',
    state_name: 'ANDHRA PRADESH',
    ministry: '',
    unit_head_name: 'CO',
    latitude: 17.36667,
    longitude: 78.46667,
  },
  {
    unit_id: 30,
    name_code: 'BHARAT PETROLEUM CORPORATION LTD KOCHI REFINERY KOCHI',
    unit_name: 'BPCL KOCHI',
    bar_color: 'green',
    state_name: 'KERALA',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 9.930471,
    longitude: 76.271273,
  },
  {
    unit_id: 31,
    name_code: 'BHARATIYA RESERVE BANK NOTE MUDRAN PVT LTD MYSORE',
    unit_name: 'BRBNMPL MYSORE',
    bar_color: 'lightblue',
    state_name: 'KARNATAKA',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 12.21,
    longitude: 76.49,
  },
  {
    unit_id: 32,
    name_code: 'CHENNAI PETROLEUM CORPORATION LIMITED MANALI',
    unit_name: 'CPCL MANALI',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 13.1667,
    longitude: 80.2667,
  },
  {
    unit_id: 33,
    name_code: 'CHENNAI PORT TRUST',
    unit_name: 'CHPT CHENNAI',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: 'shipping',
    unit_head_name: 'CO',
    latitude: 13.090932,
    longitude: 80.293,
  },
  {
    unit_id: 34,
    name_code: 'COCHIN  PORT TRUST',
    unit_name: 'CPT COCHIN',
    bar_color: 'green',
    state_name: 'KERALA',
    ministry: 'shipping',
    unit_head_name: 'DC',
    latitude: 9.966246,
    longitude: 76.260904,
  },
  {
    unit_id: 35,
    name_code: 'COCHIN SHIPYARD LIMITED',
    unit_name: 'CSY COCHIN',
    bar_color: 'green',
    state_name: 'KERALA',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 9.956863,
    longitude: 76.290662,
  },
  {
    unit_id: 36,
    name_code: 'DONIMALAI IRON ORE MINES',
    unit_name: 'DIOM DONIMALAI',
    bar_color: 'lightblue',
    state_name: 'KARNATAKA',
    ministry: '',
    unit_head_name: 'AC',
    latitude: 12.97021,
    longitude: 77.56029,
  },
  {
    unit_id: 37,
    name_code: 'FERTILIZERS AND CHEMICALS TRAVANCORE LIMITED UDYOGMANDAL',
    unit_name: 'FACT UDYOGMANDAL',
    bar_color: 'green',
    state_name: 'KERALA',
    ministry: '',
    unit_head_name: 'CO',
    latitude: 42.55833,
    longitude: 1.55528,
  },
  {
    unit_id: 38,
    name_code: 'GROUP HQ CHENNAI',
    unit_name: 'GP HQ CHENNAI',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: '',
    unit_head_name: 'CO',
    latitude: 13.09,
    longitude: 80.27,
  },
  {
    unit_id: 39,
    name_code: 'GROUP HQ COCHIN',
    unit_name: 'GP HQ COCHIN',
    bar_color: 'green',
    state_name: 'KERALA',
    ministry: '',
    unit_head_name: 'CO',
    latitude: 9.901199,
    longitude: 76.266935,
  },
  {
    unit_id: 40,
    name_code: 'GROUP HQ HYDERABAD',
    unit_name: 'GP HQ HYDERABAD',
    bar_color: 'brown',
    state_name: 'ANDHRA PRADESH',
    ministry: '',
    unit_head_name: 'CO',
    latitude: 16.5,
    longitude: 80.6,
  },
  {
    unit_id: 41,
    name_code: 'HINDUSTAN PETROLEUM CORPORATION LIMITED VIZAG',
    unit_name: 'HPCL VIZAG',
    bar_color: 'brown',
    state_name: 'ANDHRA PRADESH',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 16.5,
    longitude: 80.6,
  },
  {
    unit_id: 42,
    name_code: 'INDIAN GOVERNMENT MINT HYDERABAD',
    unit_name: 'IG MINT HYDERABAD',
    bar_color: 'brown',
    state_name: 'ANDHRA PRADESH',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 16.5,
    longitude: 80.6,
  },
  {
    unit_id: 43,
    name_code: 'KAMARAJAR PORT LIMITED ENNORE',
    unit_name: 'KPL ENNORE',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: 'shipping',
    unit_head_name: 'AC',
    latitude: 11.40623,
    longitude: 76.688409,
  },
  {
    unit_id: 44,
    name_code: 'RAICHUR THERMAL POWER STATION',
    unit_name: 'RTPS RAICHUR',
    bar_color: 'lightblue',
    state_name: 'KARNATAKA',
    ministry: '',
    unit_head_name: 'CO',
    latitude: 16.2,
    longitude: 77.37,
  },
  {
    unit_id: 45,
    name_code: 'KUDREMUKH IRON ORE COMPANY LTD MANGALORE',
    unit_name: 'KIOCL MANGALORE',
    bar_color: 'lightblue',
    state_name: 'KARNATAKA',
    ministry: '',
    unit_head_name: 'AC',
    latitude: 13.21105,
    longitude: 75.068401,
  },
  {
    unit_id: 48,
    name_code: 'MANGALORE  REFINARY AND PETROCHEMICALS LIMITED MANGALORE',
    unit_name: 'MRPL MANGALORE',
    bar_color: 'lightblue',
    state_name: 'KARNATAKA',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 12.87028,
    longitude: 74.88056,
  },
  {
    unit_id: 49,
    name_code: 'NATIONAL TECHNICAL RESERCH ORGANISATION HYDERABAD',
    unit_name: 'NTRO HYDERABAD',
    bar_color: 'crimson',
    state_name: 'TELANGANA',
    ministry: '',
    unit_head_name: '',
    latitude: 17.36667,
    longitude: 78.46667,
  },
  {
    unit_id: 50,
    name_code: 'NEW MANGALORE PORT TRUST MANGALORE',
    unit_name: 'NMPT MANGALORE',
    bar_color: 'lightblue',
    state_name: 'KARNATAKA',
    ministry: 'shipping',
    unit_head_name: 'DC',
    latitude: 12.92703,
    longitude: 74.826219,
  },
  {
    unit_id: 51,
    name_code: 'NLC TAMILNADU POWER LIMITED TUTICORIN',
    unit_name: 'NTPL TUTICORIN',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: 'shipping',
    unit_head_name: 'AC',
    latitude: 8.744095,
    longitude: 78.080648,
  },
  {
    unit_id: 52,
    name_code: 'NTPC KUDGI SUPER THERMAL POWER PROJECT KUDGI',
    unit_name: 'NTPC KUDGI',
    bar_color: 'lightblue',
    state_name: 'KARNATAKA',
    ministry: '',
    unit_head_name: 'AC',
    latitude: 16.541933,
    longitude: 75.830147,
  },
  {
    unit_id: 53,
    name_code: 'NTPC TAMIL NADU ENERGY COMPANY LIMITED VALLUR',
    unit_name: 'VTPP VALLUR',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 12.831054,
    longitude: 80.049404,
  },
  {
    unit_id: 54,
    name_code: 'OIL AND NATURAL GAS CORPORATION NARSAPUR',
    unit_name: 'ONGC NARSAPUR',
    bar_color: 'brown',
    state_name: 'ANDHRA PRADESH',
    ministry: '',
    unit_head_name: 'AC',
    latitude: 16.537143,
    longitude: 81.717646,
  },
  {
    unit_id: 55,
    name_code: 'RAJIV GANDHI COMBINED CYCLE POWER PROJECT KAYAMKULAM',
    unit_name: 'KCCPP KAYAMKULAM',
    bar_color: 'green',
    state_name: 'KERALA',
    ministry: '',
    unit_head_name: 'AC',
    latitude: 9.181745,
    longitude: 76.5123,
  },
  {
    unit_id: 56,
    name_code: 'RAJIV GANDHI NINAIVAGAM SRIPERUMBUDUR',
    unit_name: 'RGN SRIPERAMBUDUR',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: '',
    unit_head_name: 'AC',
    latitude: 12.97,
    longitude: 79.95,
  },
  {
    unit_id: 57,
    name_code: 'RAMAGUNDAM SUPER THERMAL POWER STATION ',
    unit_name: 'RSTPS RAMAGUNDAM',
    bar_color: 'brown',
    state_name: 'TELANGANA',
    ministry: '',
    unit_head_name: 'CO',
    latitude: 18.8,
    longitude: 79.45,
  },
  {
    unit_id: 58,
    name_code: 'SALARJUNG MUSEUM HYDERABAD',
    unit_name: 'SJM HYDERABAD',
    bar_color: 'brown',
    state_name: 'ANDHRA PRADESH',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 17.371594,
    longitude: 78.479681375,
  },
  {
    unit_id: 59,
    name_code: 'SALEM STEEL PLANT',
    unit_name: 'SSP SALEM',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 11.65,
    longitude: 78.16667,
  },
  {
    unit_id: 60,
    name_code: 'SIMHADRI SUPER THERMAL POWER STATION SIMHADRI',
    unit_name: 'STPP SIMHADRI',
    bar_color: 'brown',
    state_name: 'ANDHRA PRADESH',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 18.539876,
    longitude: 84.131619,
  },
  {
    unit_id: 61,
    name_code: 'SINGARENI COLLIERIES COMPANY LTD SINGARENI',
    unit_name: 'SCCL SINGARENI',
    bar_color: 'crimson',
    state_name: 'TELANGANA',
    ministry: '',
    unit_head_name: 'CO',
    latitude: 17.996698,
    longitude: 79.549052,
  },
  {
    unit_id: 62,
    name_code: 'SOUTH ZONE HQ CHENNAI',
    unit_name: 'SZ HQR CHENNAI',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: '',
    unit_head_name: 'DIG',
    latitude: 13.08389,
    longitude: 80.27,
  },
  {
    unit_id: 63,
    name_code: 'SVP NATIONAL POLICE ACADEMY HYDERABAD',
    unit_name: 'SVP NPA HYDERABAD',
    bar_color: 'crimson',
    state_name: 'TELANGANA',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 17.36667,
    longitude: 78.46667,
  },
  {
    unit_id: 64,
    name_code: 'UNION TERRITORY OF LAKSHADWEEP PASSENGER EMBARKATION AND CARGO BARGES COCHIN',
    unit_name: 'UTL PAX CARGO COCHIN',
    bar_color: 'green',
    state_name: 'KERALA',
    ministry: '',
    unit_head_name: 'AC',
    latitude: null,
    longitude: null,
  },
  {
    unit_id: 65,
    name_code: 'UNIQUE IDENTIFIACTION AUTHORITY OF INDIA BANGALORE',
    unit_name: 'UIDAI BANGALORE',
    bar_color: 'lightblue',
    state_name: 'KARNATAKA',
    ministry: '',
    unit_head_name: 'DC',
    latitude: 12.96991,
    longitude: 77.59796,
  },
  {
    unit_id: 66,
    name_code: 'VISAKHAPATNAM PORT TRUST VISAKHAPATNAM  ',
    unit_name: 'VPT VISAKHAPATANAM',
    bar_color: 'brown',
    state_name: 'ANDHRA PRADESH',
    ministry: 'shipping',
    unit_head_name: 'CO',
    latitude: 17.7,
    longitude: 83.25,
  },
  {
    unit_id: 67,
    name_code: 'VOC PORT TRUST TUTICORIN',
    unit_name: 'VOCPT TUTICORIN',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: 'shipping',
    unit_head_name: 'DC',
    latitude: 8.81,
    longitude: 78.08,
  },
  {
    unit_id: 68,
    name_code: 'ZONAL ORDINANCE WORK SHOP CHENNAI',
    unit_name: 'ZOW CHENNAI',
    bar_color: 'yellow',
    state_name: 'TAMILNADU',
    ministry: '',
    unit_head_name: 'AC',
    latitude: 13.09,
    longitude: 80.27,
  },
  {
    unit_id: 69,
    name_code: 'VISAKHAPATNAM STEEL PLANT VISAKHAPATNAM',
    unit_name: 'VSP VISAKHAPATANAM',
    bar_color: 'brown',
    state_name: 'ANDHRA PRADESH',
    ministry: '',
    unit_head_name: 'CO',
    latitude: 17.728425,
    longitude: 83.223417,
  },
  {
    unit_id: 72,
    name_code: 'REGIONAL TRAINING CENTER ARAKKONAM',
    unit_name: 'RTC ARAKKONAM',
    bar_color: 'red',
    state_name: 'TAMILNADU',
    ministry: '',
    unit_head_name: 'DIG',
    latitude: 13.1,
    longitude: 79.66667,
  },
];

export default TempData;
